In [1]:
mid_score = [10,20,30]
final_score = [70,80,90]

In [2]:
total = mid_score + final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [29]:
import numpy as np

In [2]:
mid_score = np.array([10,20,30])
final_score = np.array([70,80,90])

In [3]:
total = mid_score + final_score
print(total)

[ 80 100 120]


In [5]:
print("시험 성적의 합계:",total)

시험 성적의 합계: [ 80 100 120]


In [8]:
print("시험 성적의 합계:",total/2)

시험 성적의 합계: [40. 50. 60.]


In [24]:
array_a = np.arange(0,10)
array_b = np.array(range(10))
array_c = np.arange(0,10,2)
print(array_c)

[0 2 4 6 8]


In [19]:
array_c.shape #(5,)
array_c.ndim #1
array_c.dtype #dtype('int32')
array_c.size #5

(5,)

In [25]:
array_c.itemsize #byte단위

4

In [3]:
salary = np.array([220,250,230])


In [4]:
salary = salary + 100
salary

array([320, 350, 330])

In [5]:
salary = salary * 2
salary

array([640, 700, 660])

In [19]:
players = [[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [20]:
np_players = np.array(players)
print(np_players)

[[170.   76.4]
 [183.   86.2]
 [171.   73.5]
 [176.   80.1]]


In [24]:
print('몸무게가 80이상인 선수의 정보',np_players[np_players[:,1]>=80.0])

몸무게가 80이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [28]:
print('키가 180이상인 선수의 정보',np_players[np_players[:,0]>=180.0])

키가 180이상인 선수의 정보 [[183.   86.2]]


In [49]:
revenue_in_yen = [320, 240, 450, 120, 300,320, 240, 450, 120, 300,320, 240, 450, 120, 300,320, 240, 450, 120, 300,320, 240, 450, 120, 300,320, 240, 450, 120, 300]

In [50]:
yen_array = np.array(revenue_in_yen)
yen_array

array([320, 240, 450, 120, 300, 320, 240, 450, 120, 300, 320, 240, 450,
       120, 300, 320, 240, 450, 120, 300, 320, 240, 450, 120, 300, 320,
       240, 450, 120, 300])

In [37]:
yen_array.size

30

In [51]:
won_array = yen_array * 9.7 #엔화를 원화로 변환
won_array

array([3104., 2328., 4365., 1164., 2910., 3104., 2328., 4365., 1164.,
       2910., 3104., 2328., 4365., 1164., 2910., 3104., 2328., 4365.,
       1164., 2910., 3104., 2328., 4365., 1164., 2910., 3104., 2328.,
       4365., 1164., 2910.])

In [52]:
won_array = yen_array * 9.7 + dollar_array * 1391
won_array

array([47616., 35712., 66960., 17856., 44640., 47616., 35712., 66960.,
       17856., 44640., 47616., 35712., 66960., 17856., 44640., 47616.,
       35712., 66960., 17856., 44640., 47616., 35712., 66960., 17856.,
       44640., 47616., 35712., 66960., 17856., 44640.])

In [53]:
new_array = won_array * 10
new_array

array([476160., 357120., 669600., 178560., 446400., 476160., 357120.,
       669600., 178560., 446400., 476160., 357120., 669600., 178560.,
       446400., 476160., 357120., 669600., 178560., 446400., 476160.,
       357120., 669600., 178560., 446400., 476160., 357120., 669600.,
       178560., 446400.])

In [47]:
dollar_array = np.array([32,24,45,12,30,32,24,45,12,30,32,24,45,12,30,32,24,45,12,30,32,24,45,12,30,32,24,45,12,30])
dollar_array

array([32, 24, 45, 12, 30, 32, 24, 45, 12, 30, 32, 24, 45, 12, 30, 32, 24,
       45, 12, 30, 32, 24, 45, 12, 30, 32, 24, 45, 12, 30])

In [48]:
won_array = dollar_array * 1391.34
won_array

array([44522.88, 33392.16, 62610.3 , 16696.08, 41740.2 , 44522.88,
       33392.16, 62610.3 , 16696.08, 41740.2 , 44522.88, 33392.16,
       62610.3 , 16696.08, 41740.2 , 44522.88, 33392.16, 62610.3 ,
       16696.08, 41740.2 , 44522.88, 33392.16, 62610.3 , 16696.08,
       41740.2 , 44522.88, 33392.16, 62610.3 , 16696.08, 41740.2 ])

In [54]:
won_array.astype("int64")

array([47616, 35712, 66960, 17856, 44640, 47616, 35712, 66960, 17856,
       44640, 47616, 35712, 66960, 17856, 44640, 47616, 35712, 66960,
       17856, 44640, 47616, 35712, 66960, 17856, 44640, 47616, 35712,
       66960, 17856, 44640], dtype=int64)

In [55]:
new_array = won_array*100
print(new_array)

[4761600. 3571200. 6696000. 1785600. 4464000. 4761600. 3571200. 6696000.
 1785600. 4464000. 4761600. 3571200. 6696000. 1785600. 4464000. 4761600.
 3571200. 6696000. 1785600. 4464000. 4761600. 3571200. 6696000. 1785600.
 4464000. 4761600. 3571200. 6696000. 1785600. 4464000.]


In [57]:
print('won_array에서 수익이 50000이하인 날은',won_array[won_array<=50000])

won_array에서 수익이 50000이하인 날은 [47616. 35712. 17856. 44640. 47616. 35712. 17856. 44640. 47616. 35712.
 17856. 44640. 47616. 35712. 17856. 44640. 47616. 35712. 17856. 44640.
 47616. 35712. 17856. 44640.]


In [58]:
sad_days_revenue = won_array[won_array<=50000]
sad_days_revenue

array([47616., 35712., 17856., 44640., 47616., 35712., 17856., 44640.,
       47616., 35712., 17856., 44640., 47616., 35712., 17856., 44640.,
       47616., 35712., 17856., 44640., 47616., 35712., 17856., 44640.])