In [3]:
import numpy as np

In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
z = np.random.random((3,3,3))
print(z)

[[[0.61438521 0.28458828 0.04060399]
  [0.64733294 0.54497182 0.72180984]
  [0.14470151 0.0349018  0.11552486]]

 [[0.55005741 0.32746066 0.62098993]
  [0.53357307 0.46446687 0.6308847 ]
  [0.79029921 0.58125011 0.05153785]]

 [[0.6234162  0.01742244 0.86505562]
  [0.05065175 0.22320114 0.36859445]
  [0.18223801 0.29829946 0.74690596]]]


In [27]:
z = np.random.random(30)
print(np.mean(z))

0.5151600960894149
