In [1]:
import numpy as np

#### 연습
- 1부터 50까지의 짝수만 원소로 갖는 넘파이 배열 생성

In [5]:
arr1 = np.arange(2,51,2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

- 0을 원소로 갖는 4*4배열 생성
- 1을 원소로 갖는 10*10 배열 생성
- 본인이 좋아하는 숫자를 원소로 갖는 7*4 배열 생성

In [7]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr1 = np.ones((10,10))
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
arr2 = np.full((7,4),3)
arr2

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

- 1부터 100까지 원소 중 3의 배수를 원소로 갖는 넘파이 배열 생성

In [12]:
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

- 만들어진 3의 배수를 원소로 갖는 넘파이 배열의 개수를, reshape함수를 이용하여 2차원 배열을 생성하시오.
- 생선된 2차원 배열의 크기를 구하시오.

In [19]:
arr.size

33

In [22]:
arr2 = arr.reshape(3,11)
arr2

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

In [25]:
arr2.shape

(3, 11)

In [26]:
import random

- 1. 0 ~ 1사이의 값을 랜덤하게 가지는 6*4 배열을 생성하시오.
- 2. 1 ~ 100 사이의 값을 랜덤하게 가지는 5 * 5 배열을 생성하시오.
- 3. astype을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸시오. 

In [33]:
arr = np.random.rand(6,4)
arr

array([[0.76488813, 0.91760178, 0.08849058, 0.6245042 ],
       [0.5780498 , 0.7040634 , 0.70011824, 0.39215145],
       [0.50974713, 0.93837119, 0.07718618, 0.30754116],
       [0.15160753, 0.54203009, 0.89603808, 0.77401675],
       [0.5492003 , 0.37780529, 0.4471306 , 0.80810959],
       [0.61672205, 0.77587157, 0.70063211, 0.93296059]])

In [32]:
arr2 = np.random.randint(1,100,size=(5,5))
arr2

array([[83, 90, 61, 76, 58],
       [70, 11, 92,  6, 60],
       [71, 91, 32, 29, 13],
       [44, 55,  3, 31, 85],
       [27,  4, 57, 47, 24]])

In [34]:
arr2 = arr2.astype("float64")
arr2

array([[83., 90., 61., 76., 58.],
       [70., 11., 92.,  6., 60.],
       [71., 91., 32., 29., 13.],
       [44., 55.,  3., 31., 85.],
       [27.,  4., 57., 47., 24.]])

- 주어진 배열에서 3,4,8,9 원소만 가져오기

In [35]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
print(x[:,3:])


[[3 4]
 [8 9]]


In [45]:
print(x[1,1:4])

[6 7 8]


In [46]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- 1. (3,8,13)원소 가져오기
- 2. (5,6,7,8,9)원소 가져오기
- 3. (1,2,3,6,7,8)원소 가져오기

In [53]:
print(y[:,3])

[ 3  8 13]


In [51]:
print(y[1,:])

[5 6 7 8 9]


In [50]:
print(y[:2,1:4])

[[1 2 3]
 [6 7 8]]


In [54]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- arr2d 에서 5보다 작거나 같은 값만 추출하시오

In [61]:
print(arr2d[arr2d <= 5])

[1 2 3 4 5]


In [64]:
print(arr2d[arr2d % 3 == 0])

[ 3  6  9 12]


- & : and
- | : or

In [68]:
x = np.random.randint(1, 100, size=10)
x

array([32, 85, 15, 82, 88, 63, 91, 71, 80, 57])

- x에서 2의 배수만 추출하기
- x에서 60 이상의 수만 추출하기

In [73]:
print(x[x % 2 == 0])

[32 82 88 80]


In [74]:
print(x[x > 60])

[85 82 88 63 91 71 80]


- x에서 30보다 크고 70보다 작은 수만 추출하기
- x에서 60보다 크거나 홀수인 수를 추출하기

In [75]:
print(x[(x > 30) & (x < 70)])

[32 63 57]


In [79]:
print(x[(x > 60) | (x % 3 == 0)])

[85 15 82 88 63 91 71 80 57]


In [80]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [81]:
len(temp)

31

- 2019년 7월 서울 평균기온 데이터
- 기온이 25도를 넘는 날 수
- 기온이 25도를 넘는 날의 평균 기온은?

In [94]:
print(len(temp[temp > 25.0]))

21


In [90]:
temp_1 = (temp[temp > 25.0])
print(np.mean(temp_1))

26.857142857142858


In [96]:
print(np.mean(temp[temp > 25.0]))

26.857142857142858
