In [1]:
import numpy as np

#### 연습
- 1부터 50까지의 짝수만 원소로 갖는 넘파이 배열 생성

In [2]:
arr1 = np.arange(2,51,2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

- 0을 원소로 갖는 4*4배열 생성
- 1을 원소로 갖는 10*10 배열 생성
- 본인이 좋아하는 숫자를 원소로 갖는 7*4 배열 생성

In [3]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr1 = np.ones((10,10))
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
arr2 = np.full((7,4),3)
arr2

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

- 1부터 100까지 원소 중 3의 배수를 원소로 갖는 넘파이 배열 생성

In [6]:
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

- 만들어진 3의 배수를 원소로 갖는 넘파이 배열의 개수를, reshape함수를 이용하여 2차원 배열을 생성하시오.
- 생선된 2차원 배열의 크기를 구하시오.

In [7]:
arr.size

33

In [8]:
arr2 = arr.reshape(3,11)
arr2

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

In [9]:
arr2.shape

(3, 11)

In [10]:
import random

- 1. 0 ~ 1사이의 값을 랜덤하게 가지는 6*4 배열을 생성하시오.
- 2. 1 ~ 100 사이의 값을 랜덤하게 가지는 5 * 5 배열을 생성하시오.
- 3. astype을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸시오. 

In [11]:
arr = np.random.rand(6,4)
arr

array([[0.53744764, 0.15914467, 0.46844516, 0.59771084],
       [0.46855831, 0.41995134, 0.71735639, 0.57650126],
       [0.50561425, 0.70051138, 0.40044551, 0.78853164],
       [0.70644881, 0.76964909, 0.75008218, 0.25576585],
       [0.36806918, 0.6532862 , 0.99060813, 0.28874054],
       [0.94942633, 0.29734149, 0.06753943, 0.90693668]])

In [12]:
arr2 = np.random.randint(1,100,size=(5,5))
arr2

array([[28, 72, 47, 26, 84],
       [34, 27, 61, 57, 45],
       [91, 95, 22, 26, 96],
       [35, 90, 54, 16, 11],
       [29, 99, 31, 46, 28]])

In [13]:
arr2 = arr2.astype("float64")
arr2

array([[28., 72., 47., 26., 84.],
       [34., 27., 61., 57., 45.],
       [91., 95., 22., 26., 96.],
       [35., 90., 54., 16., 11.],
       [29., 99., 31., 46., 28.]])

- 주어진 배열에서 3,4,8,9 원소만 가져오기

In [14]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
print(x[:,3:])


[[3 4]
 [8 9]]


In [16]:
print(x[1,1:4])

[6 7 8]


In [17]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- 1. (3,8,13)원소 가져오기
- 2. (5,6,7,8,9)원소 가져오기
- 3. (1,2,3,6,7,8)원소 가져오기

In [18]:
print(y[:,3])

[ 3  8 13]


In [19]:
print(y[1,:])

[5 6 7 8 9]


In [20]:
print(y[:2,1:4])

[[1 2 3]
 [6 7 8]]


In [21]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- arr2d 에서 5보다 작거나 같은 값만 추출하시오

In [22]:
print(arr2d[arr2d <= 5])

[1 2 3 4 5]


In [23]:
print(arr2d[arr2d % 3 == 0])

[ 3  6  9 12]


- & : and
- | : or

In [24]:
x = np.random.randint(1, 100, size=10)
x

array([18, 74, 62, 89, 66, 16, 55, 27, 19, 32])

- x에서 2의 배수만 추출하기
- x에서 60 이상의 수만 추출하기

In [25]:
print(x[x % 2 == 0])

[18 74 62 66 16 32]


In [26]:
print(x[x > 60])

[74 62 89 66]


- x에서 30보다 크고 70보다 작은 수만 추출하기
- x에서 60보다 크거나 홀수인 수를 추출하기

In [27]:
print(x[(x > 30) & (x < 70)])

[62 66 55 32]


In [28]:
print(x[(x > 60) | (x % 3 == 0)])

[18 74 62 89 66 27]


In [29]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [30]:
len(temp)

31

- 2019년 7월 서울 평균기온 데이터
- 기온이 25도를 넘는 날 수
- 기온이 25도를 넘는 날의 평균 기온은?

In [31]:
print(len(temp[temp > 25.0]))

21


In [32]:
temp_1 = (temp[temp > 25.0])
print(np.mean(temp_1))

26.857142857142858


In [33]:
print(np.mean(temp[temp > 25.0]))

26.857142857142858


- y 원소들의 평균, 합, 최대값, 최소값, 분산, 중앙값, 표준편차를 구해봅시다

In [34]:
y = np.random.randint(100, size=(3,5))
print(y)

[[52 71 30 42 99]
 [15 17 86 89 15]
 [15 87 43 12 36]]


In [47]:
print(np.mean(y)) #평균 47.266666666666666
print(np.sum(y)) #합 709
print(y.max()) #최대값 99
print(y.min()) #최소값 12
print(y.var()) #분산 922.4622222222223
print(np.median(y)) #중앙값 42.0
print(y.std()) # 표준편차 30.372063186787663

47.266666666666666
709
99
12
922.4622222222223
42.0
30.372063186787663
