In [1]:
mid_score = [10,20,30]
final_score = [70,80,90]

In [2]:
total = mid_score + final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [2]:
import numpy as np

In [2]:
mid_score = np.array([10,20,30])
final_score = np.array([70,80,90])

In [3]:
total = mid_score + final_score
print(total)

[ 80 100 120]


In [5]:
print("시험 성적의 합계:",total)

시험 성적의 합계: [ 80 100 120]


In [8]:
print("시험 성적의 합계:",total/2)

시험 성적의 합계: [40. 50. 60.]


In [24]:
array_a = np.arange(0,10)
array_b = np.array(range(10))
array_c = np.arange(0,10,2)
print(array_c)

[0 2 4 6 8]


In [19]:
array_c.shape #(5,)
array_c.ndim #1
array_c.dtype #dtype('int32')
array_c.size #5

(5,)

In [25]:
array_c.itemsize #byte단위

4

In [3]:
salary = np.array([220,250,230])


In [4]:
salary = salary + 100
salary

array([320, 350, 330])

In [5]:
salary = salary * 2
salary

array([640, 700, 660])

In [19]:
players = [[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [20]:
np_players = np.array(players)
print(np_players)

[[170.   76.4]
 [183.   86.2]
 [171.   73.5]
 [176.   80.1]]


In [24]:
print('몸무게가 80이상인 선수의 정보',np_players[np_players[:,1]>=80.0])

몸무게가 80이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [28]:
print('키가 180이상인 선수의 정보',np_players[np_players[:,0]>=180.0])

키가 180이상인 선수의 정보 [[183.   86.2]]
